[db-pooler]
addr = { host = "localhost", port = 8201 }
name = "backend"
user = "postgres"
password = "develove"

[etcd]
namespace = "local"
addr = { host = "127.0.0.1", port = 8121 }
user = ""
password = ""

[datastore]
rpc-listen-addr = { host = "127.0.0.1", port = 8191 }
# id = "i-something-special"
pid-file = "./datastore.pid"
event-loop = "uvloop"

[debug]
enabled = true
