name: timeline-check

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]
  merge_group:

jobs:
  pr-number-assign:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip:changelog') && github.event.pull_request.number != null }}
    uses: ./.github/workflows/pr-number-assign.yml

  towncrier:
    needs: [pr-number-assign]
    runs-on: ubuntu-latest
    steps:
    - name: Sparse-checkout
      uses: snow-actions/sparse-checkout@v1.2.0
      with:
        patterns: |
          changes
          scripts
        filter: "blob:limit=1"
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        check-latest: true
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools
        python -m pip install -U towncrier~=22.12
    - name: Check existence of news fragment
      run: |
        git fetch --no-tags origin +refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH}
        python -m towncrier.check --compare-with=origin/${BASE_BRANCH}
      env:
        BASE_BRANCH: ${{ github.base_ref }}
